# Easy Commit Configuration Example
# Copy this file to .easy-commit.yaml and modify as needed

# Commit validation rules
commit:
  # Maximum length for commit description (default: 72)
  maxDescriptionLength: 72

  # Maximum length for commit body (default: 500)
  maxBodyLength: 500

  # Characters not allowed in commit description (default: empty array)
  invalidChars: []
  # Example: ['@', '#', '$']

# Timeout configurations (in milliseconds)
timeouts:
  # Timeout for validation operations (default: 5000ms = 5s)
  validation: 5000

  # Timeout for git commands (default: 5000ms = 5s)
  gitCommand: 5000

  # Timeout for user input in TUI (default: 300000ms = 5min)
  userInput: 300000

  # Timeout for context operations (default: 60000ms = 1min)
  context: 60000

# Validator configuration
validator:
  # Number of concurrent validation workers (default: 4)
  # Range: 1-16
  workers: 4

# Logger configuration
logger:
  # Log level: DEBUG, INFO, WARN, ERROR, SILENT (default: INFO)
  level: SILENT
  # Use DEBUG for troubleshooting
  # Use SILENT to disable logging
